version: "3.8"

services:
  radarr-cleaner:
    build: .
    container_name: sonarrcleaner
    restart: no
    environment:
      API: ${API}
      IP: ${IP}
      QBIT_TIME: ${QBIT_TIME}
      QBITIP: ${QBITIP}
      QBITUSER: ${QBITUSER}
      QBITPASS: ${QBITPASS}
      HOMEASSISTANTWEBHOOK: ${HOMEASSISTANTWEBHOOK}
      DATABASE_URL: ${DATABASE_URL}
    dns:
      - 1.1.1.1
      - 1.0.0.1





